version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: brask:latest
    container_name: brask-app
    restart: unless-stopped
    networks:
      - brask-app
    ports:
      - "8080:80"

networks:
  brask-app:
    driver: bridge